### PR TITLE
add zig-time, zig-md2 and zig-md4

### PR DESCRIPTION
**Pull request by deatil**
hi, i add zig-time, zig-md2 and zig-md4.

### CODE REVIEW

**Comment by C-BJ** [comment]
thanks

**Comment by C-BJ** [comment]
GitHub has some issues, I will merge the PR later.

**Comment by deatil** [comment]
hi, @C-BJ pr have no merge?

**Comment by C-BJ** [comment]
> Merge attempt failed
Head branch is out of date. Review and try the merge again.

Maybe you should update your branch yourself?

**Comment by deatil** [comment]
@C-BJ i reopen a pr

**Pull request closed without merging**
