### PR TITLE
Add zig-time

### PR DESCRIPTION
**Pull request by deatil**
Add zig-time

### CODE REVIEW

**Comment by FObersteiner** [comment]
is this a fork of https://github.com/nektro/zig-time ?

**Comment by FObersteiner** [comment]
ok, just got confused by the identical name. To clarify, I'm the author of this post on ziggit: https://ziggit.dev/t/state-of-datetime-handling-in-zig/ and have recently added some datetime libs to https://github.com/zigcc/awesome-zig?tab=readme-ov-file#date-time-and-timezones - in case you need more inspiration :)

**Comment by C-BJ** [comment]
Remember to arrange projects in alphabetical order.

**Comment by deatil** [comment]
> And remember to arrange projects in alphabetical order.

ok

**Comment by deatil** [comment]
> ok, just got confused by the identical name. To clarify, I'm the author of this post on ziggit: https://ziggit.dev/t/state-of-datetime-handling-in-zig/ and have recently added some datetime libs to https://github.com/zigcc/awesome-zig?tab=readme-ov-file#date-time-and-timezones - in case you need more inspiration :)

ok, i will see.

**Pull request merged**
